[character]
success_symbol = '[󰘧](bold green)'
error_symbol = '[󰘧](bold red)'

[directory]
truncate_to_repo = false

[dotnet]
# Remove project.json from detect_files to prevent nx projects from triggering this module
detect_files = ["global.json", "Directory.Build.props", "Directory.Build.targets", "Packages.props"]

[lua]
symbol = " "

[git_branch]
symbol = " "

[buf]
disabled = true

[custom.sapling_commit]
command = "sl log -r . -T \"{ifeq(activebookmark, \\\"\\\", \\\"{node|short}\\\", \\\"{activebookmark}\\\")}\" | awk 'NR==1{print \"󰌪 \" $0}'"
when = "sl show > /dev/null 2>&1; test $? -eq 0"
style = "#a6da95"
format = "on [$output]($style) "
shell = ["zsh"]

# [custom.saplings_status]
# command = "sl status | awk '{symbols[\"A\"]=\"+\"; symbols[\"R\"]=\"✘\"; symbols[\"M\"]=\"!\"; symbols[\"?\"]=\"?\"; status = status symbols[$1]} END {if (status) print \"[\" status \"]\"}'"
# when = "sl show > /dev/null 2>&1; test $? -eq 0"
# style = "bold red"
# format = " [$output]($style)"
# shell = ["zsh"]

[custom.kitty_layout]
command = 'kitty @ kitten get_layout.py'
when = ''' [ "$(kitty @ kitten get_layout.py)" = "stack" ] '''
symbol = " "
format = 'in [$symbol]($style)'
style = '#c6a0f6'
shell = ['zsh']
