[character]
success_symbol = '[󰘧](bold green)'
error_symbol = '[󰘧](bold red)'

[directory]
truncate_to_repo = false

[dotnet]
# Remove project.json from detect_files to prevent nx projects from triggering this module
detect_files = ["global.json", "Directory.Build.props", "Directory.Build.targets", "Packages.props"]

[lua]
symbol = " "

[git_branch]
symbol = " "

[buf]
disabled = true

[custom.kitty_layout]
command = 'kitty @ kitten get_layout.py'
when = ''' [ "$(kitty @ kitten get_layout.py)" = "stack" ] '''
symbol = " "
format = 'in [$symbol]($style)'
style = '#c6a0f6'
shell = ['zsh']
